name: CI
on: [push]
jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: Configure
        run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: Build
        run: cmake --build _build --config RelWithDebInfo
  build-windows:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: Configure
        run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: Build
        run: cmake --build _build --config RelWithDebInfo
  build-mac:
    runs-on: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: Install Boost
        run: brew install boost
      - name: Configure
        run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: Build
        run: cmake --build _build --config RelWithDebInfo
