name: CI
on: [push]
jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -E make_directory _build && cmake -E chdir _build cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: build
        run: cmake -E chdir _build cmake --build . --config RelWithDebInfo
  build-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -E make_directory _build && cmake -E chdir _build cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: build
        run: cmake -E chdir _build cmake --build . --config RelWithDebInfo
  build-mac:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -E make_directory _build && cmake -E chdir _build cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBoost_USE_STATIC_LIBS=ON
      - name: build
        run: cmake -E chdir _build cmake --build . --config RelWithDebInfo
